[theme]
primaryColor = "#087F71"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182B42"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
